server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-password: solvechallenge
    key-alias: tomcat
    key-store-type: PKCS12
  servlet:
    context-path: /api

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: app
        id.new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/solve_challenge?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: