server:
  port: 8082
  servlet:
    context-path: /api

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: app
        id.new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://206.189.151.97:3306/solve_challenge
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver